### ISSUE TITLE
As a developer, I want to use MongoDB and Mongoose ODM as my database.

### ISSUE THREAD

**Issue by wol42verine** [savannahmarshall/Project-3#5]

**Comment by savannahmarshall** [comment]
As a developer, I want to use MongoDB and Mongoose ODM as my database.

Acceptance Criteria:
- It is done when MongoDB is installed and connected to MongoDB Atlas.
- A connection to the MongoDB database is established using Mongoose in the application (mongoose.connect).
- At least one Mongoose schema and model is created to represent a data structure.
- The database connection is properly handled with error catching and logging in the console.
- The application can seed initial data into MongoDB using the Mongoose model.
- The application is able to use Mongoose queries and handle responses asynchronously, ensuring proper error handling with try/catch blocks or .catch() on promises.
