### ISSUE TITLE
As a user, I want to enter my username and password to log in to my account/create a new account.

### ISSUE THREAD

**Issue by wol42verine** [savannahmarshall/Project-3#6]

**Comment by savannahmarshall** [comment]
As a user, I want to enter my username and password to log in to my account/create a new account. 

Acceptance Criteria:
It is done when:

Form Validation:
-The registration form should require a username and password.
-The username should be unique across all users.
-The password must be a minimum of 8 characters long and should be securely hashed before storing.

Database Storage:
Upon successful registration, the user’s data (username and hashed password) should be saved to the users collection in the database.

Feedback to User:
Upon successfully creating a new account, the user should be automatically logged in. If there are any issues during the registration process, the user should receive a clear and informative error message detailing the problem.
